import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Product } from '../../models/product.model';
import { ProductService } from '../../services/product.service';

@Component({
  selector: 'app-add-product',
  standalone: false,
  templateUrl: './add-product.html',
  styleUrl: './add-product.css'
})
export class AddProduct implements OnInit {
  // Form data
  product: Product = {
    id: undefined as any,
    name: '',
    description: '',
    price: 0,
    quantity: 1,
    category: '',
    image: ''
  };

  // Component state
  isEditMode = false;
  loading = false;
  saving = false;
  error: string | null = null;
  success: string | null = null;

  // Form validation
  formErrors: {[key: string]: string} = {};

  constructor(
    private productService: ProductService,
    private router: Router,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    // Check if we're in edit mode (product ID in route params)
    const productId = this.route.snapshot.paramMap.get('id');
    if (productId) {
      this.isEditMode = true;
      this.loadProduct(Number(productId));
    }
  }

  loadProduct(id: number): void {
    this.loading = true;
    this.error = null;
    this.productService.getProductById(id).subscribe({
      next: (product) => {
        this.product = { ...product };
        this.loading = false;
      },
      error: (err) => {
        console.error('Failed to load product', err);
        this.error = 'Produit non trouvé';
        this.loading = false;
      }
    });
  }

  validateForm(): boolean {
    this.formErrors = {};
    let isValid = true;

    // Validate name
    if (!this.product.name?.trim()) {
      this.formErrors['name'] = 'Le nom du produit est requis';
      isValid = false;
    } else if (this.product.name.trim().length < 2) {
      this.formErrors['name'] = 'Le nom doit contenir au moins 2 caractères';
      isValid = false;
    }

    // Validate description
    // Description is optional as it will be auto-generated by backend
    if (this.product.description?.trim() && this.product.description.trim().length < 10) {
      this.formErrors['description'] = 'La description doit contenir au moins 10 caractères';
      isValid = false;
    }

    // Validate price
    if (!this.product.price || this.product.price <= 0) {
      this.formErrors['price'] = 'Le prix doit être supérieur à 0';
      isValid = false;
    }

    // Validate quantity
    if (!this.product.quantity || this.product.quantity <= 0) {
      this.formErrors['quantity'] = 'La quantité doit être supérieure à 0';
      isValid = false;
    } else if (this.product.quantity > 9999) {
      this.formErrors['quantity'] = 'La quantité ne peut pas dépasser 9999';
      isValid = false;
    } else if (!Number.isInteger(this.product.quantity)) {
      this.formErrors['quantity'] = 'La quantité doit être un nombre entier';
      isValid = false;
    }

    // Validate category
    if (!this.product.category?.trim()) {
      this.formErrors['category'] = 'La catégorie est requise';
      isValid = false;
    }

    // Validate image URL (optional)
    if (this.product.image?.trim() && !this.isValidUrl(this.product.image)) {
      this.formErrors['image'] = 'L\'URL de l\'image n\'est pas valide';
      isValid = false;
    }

    return isValid;
  }

  private isValidUrl(url: string): boolean {
    try {
      new URL(url);
      return true;
    } catch {
      return false;
    }
  }

  onSubmit(): void {
    this.error = null;
    this.success = null;

    if (!this.validateForm()) {
      return;
    }

    this.saving = true;

    if (this.isEditMode) {
      this.updateProduct();
    } else {
      this.createProduct();
    }
  }

  private createProduct(): void {
    this.productService.addProduct(this.product).subscribe({
      next: (createdProduct) => {
        console.log('Product created successfully:', createdProduct);
        this.saving = false;
        this.success = 'Produit créé avec succès!';
        // Reset form after successful creation
        setTimeout(() => {
          this.router.navigate(['/dashboard']);
        }, 2000);
      },
      error: (err) => {
        console.error('Failed to create product', err);
        this.saving = false;
        this.error = 'Impossible de créer le produit. Veuillez réessayer.';
      }
    });
  }

  private updateProduct(): void {
    this.productService.updateProduct(this.product.id, this.product).subscribe({
      next: (updatedProduct) => {
        console.log('Product updated successfully:', updatedProduct);
        this.saving = false;
        this.success = 'Produit mis à jour avec succès!';
        setTimeout(() => {
          this.router.navigate(['/dashboard']);
        }, 2000);
      },
      error: (err) => {
        console.error('Failed to update product', err);
        this.saving = false;
        this.error = 'Impossible de mettre à jour le produit. Veuillez réessayer.';
      }
    });
  }

  onCancel(): void {
    this.router.navigate(['/dashboard']);
  }

  onReset(): void {
    if (this.isEditMode) {
      // Reload the original product data
      const productId = this.route.snapshot.paramMap.get('id');
      if (productId) {
        this.loadProduct(Number(productId));
      }
    } else {
      // Reset to empty form
      this.product = {
        id: undefined as any,
        name: '',
        description: '',
        price: 0,
        quantity: 1,
        category: '',
        image: ''
      };
    }
    this.formErrors = {};
    this.error = null;
    this.success = null;
  }
}